In [1]:
import torch

In [2]:
some_tensor = torch.rand(3, 4)

print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.4796, 0.5270, 0.9684, 0.8073],
        [0.2106, 0.1822, 0.7304, 0.8966],
        [0.7187, 0.6043, 0.6421, 0.3219]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [3]:
tensor1 = torch.Tensor([1,2,3])

In [4]:
tensor1+100

tensor([101., 102., 103.])

In [5]:
tensor1*tensor1

tensor([1., 4., 9.])

In [6]:
tensor1+tensor1-(3*tensor1)

tensor([-1., -2., -3.])

In [12]:
R = torch.add(tensor1, 100)
R

tensor([101., 102., 103.])

In [11]:
Q = torch.matmul(tensor1,tensor1)
Q

tensor(14.)

In [14]:
O = torch.matmul(torch.rand(3,10),torch.rand(10,5))
O

tensor([[1.6121, 1.7075, 2.3645, 2.4383, 2.5595],
        [1.6997, 1.2077, 2.0843, 1.8431, 1.7923],
        [2.9545, 2.6260, 2.7894, 2.6547, 3.5443]])

In [16]:
U = torch.rand(3,10)
P = U.T
S = torch.mm(U,P)
S

tensor([[3.4786, 3.3636, 2.3105],
        [3.3636, 5.1464, 3.0569],
        [2.3105, 3.0569, 3.2121]])

Mean, Max, Min, Sum

In [31]:
g = torch.arange(20,500,50)
print(g.min())
print(g.max())
t = g.type(torch.float16).mean()


tensor(20)
tensor(470)


In [32]:
g.dtype

torch.int64

In [33]:
t.dtype

torch.float64