In [1]:
import torch


In [3]:
scalar = torch.tensor(7)

In [4]:
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
vector = torch.tensor([7, 7])
vector

tensor([37, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [12]:
MATRIX = torch.Tensor([[2,3],
                        [4,5]])
MATRIX

tensor([[2., 3.],
        [4., 5.]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
TENSOR = 

<function Tensor.size>

In [33]:
x = torch.Tensor([[[1,2,3],
                    [2,3,3],
                    [3,4,5]]])

In [30]:
x.shape

torch.Size([1, 3, 3])

In [31]:
x.ndim

3

In [34]:
y = torch.Tensor([[[1,2,3],
                    [2,3,3],
                    [3,4,5]],[[1,2,3],
                    [2,3,3],
                    [3,4,5]],[[1,2,3],
                    [2,3,3],
                    [3,4,5]]])

In [35]:
y.ndim

3

In [36]:
y.shape

torch.Size([3, 3, 3])

In [47]:
z = torch.Tensor([[[1,2,3],
                    [2,3,3],
                    [3,4,5]],[[1,2,3],
                    [2,3,3],
                    [3,4,5]],[[1,2,3],
                    [2,3,3],
                    [3,4,5]]])

In [48]:
z.ndim

3

In [49]:
z.shape

torch.Size([3, 3, 3])

In [50]:
C = torch.rand(3,4)

In [51]:
C

tensor([[0.3172, 0.9102, 0.6485, 0.7474],
        [0.9299, 0.6783, 0.6082, 0.6926],
        [0.3170, 0.8315, 0.4741, 0.0217]])

In [56]:
Y = torch.rand(223,223,23)
Y.shape,Y.ndim

(torch.Size([223, 223, 23]), 3)

In [65]:
W = torch.rand(2,2,3,4)

In [66]:
W

tensor([[[[0.7298, 0.8544, 0.2895, 0.3422],
          [0.6245, 0.8550, 0.6862, 0.0576],
          [0.4807, 0.0955, 0.0150, 0.5859]],

         [[0.3544, 0.7171, 0.1776, 0.7669],
          [0.8100, 0.7792, 0.7812, 0.8133],
          [0.8916, 0.7140, 0.7160, 0.9357]]],


        [[[0.6793, 0.8807, 0.8436, 0.4187],
          [0.3936, 0.6036, 0.2279, 0.8339],
          [0.3940, 0.3201, 0.2439, 0.3172]],

         [[0.3954, 0.4939, 0.7022, 0.2447],
          [0.5642, 0.1053, 0.0288, 0.3458],
          [0.3247, 0.3079, 0.3777, 0.9938]]]])

In [67]:
P = torch.ones(2,3,4)
P

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [69]:
P.dtype

torch.float32

In [70]:
P*W

tensor([[[[0.7298, 0.8544, 0.2895, 0.3422],
          [0.6245, 0.8550, 0.6862, 0.0576],
          [0.4807, 0.0955, 0.0150, 0.5859]],

         [[0.3544, 0.7171, 0.1776, 0.7669],
          [0.8100, 0.7792, 0.7812, 0.8133],
          [0.8916, 0.7140, 0.7160, 0.9357]]],


        [[[0.6793, 0.8807, 0.8436, 0.4187],
          [0.3936, 0.6036, 0.2279, 0.8339],
          [0.3940, 0.3201, 0.2439, 0.3172]],

         [[0.3954, 0.4939, 0.7022, 0.2447],
          [0.5642, 0.1053, 0.0288, 0.3458],
          [0.3247, 0.3079, 0.3777, 0.9938]]]])

In [73]:
e = torch.arange(end= 200, start=20, step=40)
e

tensor([ 20,  60, 100, 140, 180])

In [74]:
s = torch.zeros_like(e)
s

tensor([0, 0, 0, 0, 0])

In [86]:
f = torch.arange(start=23,end=324,step=23,dtype= torch.float32)
f

tensor([ 23.,  46.,  69.,  92., 115., 138., 161., 184., 207., 230., 253., 276.,
        299., 322.])