In [1]:
import torch

In [2]:
x = torch.arange(12, dtype = torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [7]:
x.size()

torch.Size([12])

In [6]:
x.numel()

12

In [9]:
x.shape

torch.Size([12])

In [11]:
y = x.reshape(2,6)
y

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])

In [12]:
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [13]:
z = x.reshape(2,3,2)
z

tensor([[[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.]],

        [[ 6.,  7.],
         [ 8.,  9.],
         [10., 11.]]])

In [14]:
a = torch.zeros(3, 3, 4)
a

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [17]:
b = torch.randn(4, 3, 3)
b

tensor([[[-1.9625,  1.0021, -0.1668],
         [ 1.3498,  1.6977,  0.1457],
         [-1.1550,  0.7281, -0.2768]],

        [[-0.8051, -0.3081, -0.6243],
         [-1.2732,  0.6094,  0.3691],
         [-0.8954,  0.8811, -1.1816]],

        [[-0.3966,  2.3214, -1.4218],
         [-0.1756, -0.2441, -0.1347],
         [ 0.7496, -1.4146, -0.9250]],

        [[ 0.4770, -0.2622,  0.3619],
         [ 1.6171, -1.1603,  0.4275],
         [ 1.2885,  0.4253,  0.6352]]])

In [18]:
c = torch.ones(2, 2, 4)
c

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [19]:
d =torch.tensor([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
d

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [20]:
d[-2]

tensor([4, 5, 6])

In [21]:
d[0]

tensor([1, 2, 3])

In [42]:
d[1:3]

tensor([[4, 5, 6],
        [7, 8, 9]])

task done upto indexing and slicing from d2l pytorch ndarry